baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Hugo Site"

[[module.imports]]
path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify"
version = "v1.1.0"  # Replace with a stable version if needed
